[project]
name = "modal-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "modal",
    "fastapi",
    "pydantic",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
